### ISSUE TITLE
Use a framework instead?

### ISSUE THREAD

**Issue by xvilo** [janvankampen/heldnodig-site#13]
## What
Currently, the setup is all custom. While this works for a few pages, it could be hard maintaining its code and **security** wise. If we want people to help out it's best to have a common ground so people are set up quickly. 

I would suggest porting this to Symfony 4.3 (which is LTS), it would give us the following advantages:
- Common framework a lot of developers know
- Twig/PHP
- Doctrine for Database, so we don't have to deal with the 'generated' models. (not sure how they are generated even). 

It's probably a good idea to not think too long about this, as the codebase and database are still small, so migrating would take too much effort. 

## How
I would suggest creating another branch (named `Symfony` in which we can collaborate, and create issues tagged with a `Symfony` tag so we can easily see who does what. 

We can then create small PR's into the `Symfony` branch, while we can still support current code by merging directly into master. 

As we think everything is ready for an MVP, we can then merge Symfony into master without too much effort.

## Other things?
I'm eager to know what your opinions are, and I, definitely, did not want to push things through. Just opening a discussion here, and let's see what comes out.

**Comment by ferrydeboer** [comment]
I agree that this is definitely be beneficial on the long run. It will aid easier development instead of reinventing the wheel on certain things.

Would this require any migrations initially? From what I see we can just stick Doctrine on top of the existing database. And having support for things as migrations is obviously a big plus.

If there is no urgent need for features at the moment this can probably be done fairly quickly. But it will only be really beneficial if it aids a roadmap for the somewhat longer term!

**Comment by xvilo** [comment]
It seems like it, however, I would like to revise the current models and maybe change it a bit here there if needed. So keep a migration in mind. If this is something that is wanted I would happily help out by making the first steps.

**Comment by ferrydeboer** [comment]
I was contemplating on this again because it does feel valuable. I know there are some thing that only Jan can do now that we need some admin functions for. What if we start building that admin site in a subdirectory first. This gives us the opportunity to write new code on the side without initially breaking the old code. This way we can make a smoother transition maybe.

What's your opinion on this @xvilo and @janvankampen ? Will this conflict with the current setup?

**Comment by xvilo** [comment]
Well, I suppose that would not really matter to create a different admin site. 
We either want to:
- Split backend and frontend, by creating a Symfony based API for example. And then plug the frontend into it
- Make the same site in Symfony with current models, test everything and deploy.

I suppose splitting does not really matter, so I would go for option one and it should not gives too many headaches
